##
## Copyright 2013 - 2015 Marco Nehmeier (nehmeier@informatik.uni-wuerzburg.de)
## Copyright 2015 Oliver Heimlich (oheim@posteo.de)
## 
## Original author: Marco Nehmeier (unit tests in libieeep1788)
## Converted into portable ITL format by Oliver Heimlich with minor corrections.
## 
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
## 
##     http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
%!shared
%!  ## Disable warnings when creating NaIs
%!  warning ("off", "interval:NaI")
%! ## Test library imports
%!function s = to_string (x)
%!    if (isnumeric (x))
%!        s = num2str (x);
%!    elseif (isa (x, 'infsup'))
%!        s = intervaltotext (x);
%!    else
%!        # x probably is a char.
%!        s = x;
%!    endif
%!endfunction
%
%!function assert_equals (x, y)
%!    if (isa (x, "infsup"))
%!        assert (eq (x, y));
%!    else
%!        assert (isequal (x, y));
%!    endif
%!endfunction
%
%!function n = decval (dec)
%! n = find (strcmp (dec, {"ill", "trv", "def", "dac", "com"}));
%!endfunction

%!test "minimal_empty_test";
%! assert_equals (...
%!    isempty (infsup ()), ...
%!    true)
%! assert_equals (...
%!    isempty (infsup (-inf, inf)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (1.0, 2.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (-1.0, 2.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (-3.0, -2.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (-inf, 2.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (-inf, 0.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (-inf, -0.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (0.0, inf)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (-0.0, inf)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (-0.0, 0.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (0.0, -0.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (0.0, 0.0)), ...
%!    false)
%! assert_equals (...
%!    isempty (infsup (-0.0, -0.0)), ...
%!    false)

%!test "minimal_empty_dec_test";
%! assert_equals (...
%!    isempty (infsupdec (-inf, inf, "def")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (1.0, 2.0, "com")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (-1.0, 2.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (-3.0, -2.0, "dac")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (-inf, 2.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (-inf, 0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (-inf, -0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (0.0, inf, "def")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (-0.0, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (-0.0, 0.0, "com")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (0.0, -0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (0.0, 0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isempty (infsupdec (-0.0, -0.0, "trv")), ...
%!    false)

%!test "minimal_entire_test";
%! assert_equals (...
%!    isentire (infsup ()), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    isentire (infsup (1.0, 2.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-1.0, 2.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-3.0, -2.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-inf, 2.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-inf, 0.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-inf, -0.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (0.0, inf)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-0.0, inf)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-0.0, 0.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (0.0, -0.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (0.0, 0.0)), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup (-0.0, -0.0)), ...
%!    false)

%!test "minimal_entire_dec_test";
%! assert_equals (...
%!    isentire (infsup ()), ...
%!    false)
%! assert_equals (...
%!    isentire (infsup ()), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    isentire (infsupdec (-inf, inf, "def")), ...
%!    true)
%! assert_equals (...
%!    isentire (infsupdec (-inf, inf, "dac")), ...
%!    true)
%! assert_equals (...
%!    isentire (infsupdec (1.0, 2.0, "com")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-1.0, 2.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-3.0, -2.0, "dac")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-inf, 2.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-inf, 0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-inf, -0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (0.0, inf, "def")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-0.0, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-0.0, 0.0, "com")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (0.0, -0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (0.0, 0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isentire (infsupdec (-0.0, -0.0, "trv")), ...
%!    false)

%!test "minimal_nai_dec_test";
%! assert_equals (...
%!    isnai (infsupdec (-inf, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-inf, inf, "def")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-inf, inf, "dac")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (1.0, 2.0, "com")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-1.0, 2.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-3.0, -2.0, "dac")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-inf, 2.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-inf, 0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-inf, -0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (0.0, inf, "def")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-0.0, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-0.0, 0.0, "com")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (0.0, -0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (0.0, 0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    isnai (infsupdec (-0.0, -0.0, "trv")), ...
%!    false)

%!test "minimal_equal_test";
%! assert_equals (...
%!    eq (infsup (1.0, 2.0), infsup (1.0, 2.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (1.0, 2.0) == infsup (1.0, 2.0), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (1.0, 2.1), infsup (1.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 2.1) == infsup (1.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    eq (infsup (), infsup ()), ...
%!    true)

%! assert_equals (...
%!    infsup () == infsup (), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (), infsup (1.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup () == infsup (1.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    eq (infsup (-inf, inf), infsup (-inf, inf)), ...
%!    true)

%! assert_equals (...
%!    infsup (-inf, inf) == infsup (-inf, inf), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (1.0, 2.4), infsup (-inf, inf)), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 2.4) == infsup (-inf, inf), ...
%!    false)
%! assert_equals (...
%!    eq (infsup (1.0, inf), infsup (1.0, inf)), ...
%!    true)

%! assert_equals (...
%!    infsup (1.0, inf) == infsup (1.0, inf), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (1.0, 2.4), infsup (1.0, inf)), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 2.4) == infsup (1.0, inf), ...
%!    false)
%! assert_equals (...
%!    eq (infsup (-inf, 2.0), infsup (-inf, 2.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-inf, 2.0) == infsup (-inf, 2.0), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (-inf, 2.4), infsup (-inf, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (-inf, 2.4) == infsup (-inf, 2.0), ...
%!    false)
%! assert_equals (...
%!    eq (infsup (-2.0, 0.0), infsup (-2.0, 0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-2.0, 0.0) == infsup (-2.0, 0.0), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (-0.0, 2.0), infsup (0.0, 2.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-0.0, 2.0) == infsup (0.0, 2.0), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (-0.0, -0.0), infsup (0.0, 0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-0.0, -0.0) == infsup (0.0, 0.0), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (-0.0, 0.0), infsup (0.0, 0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-0.0, 0.0) == infsup (0.0, 0.0), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (0.0, -0.0), infsup (0.0, 0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (0.0, -0.0) == infsup (0.0, 0.0), ...
%!    true)

%!test "minimal_equal_dec_test";
%! assert_equals (...
%!    eq (infsupdec (1.0, 2.0, "def"), infsupdec (1.0, 2.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "def") == infsupdec (1.0, 2.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    eq (infsupdec (1.0, 2.1, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.1, "trv") == infsupdec (1.0, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    eq (infsup (), infsup ()), ...
%!    true)

%! assert_equals (...
%!    infsup () == infsup (), ...
%!    true)
%! assert_equals (...
%!    eq (infsup (), infsupdec (1.0, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsup () == infsupdec (1.0, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    eq (infsup (), infsupdec (1.0, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsup () == infsupdec (1.0, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    eq (infsupdec (-inf, inf, "def"), infsupdec (-inf, inf, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-inf, inf, "def") == infsupdec (-inf, inf, "trv"), ...
%!    true)
%! assert_equals (...
%!    eq (infsupdec (1.0, 2.4, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.4, "trv") == infsupdec (-inf, inf, "trv"), ...
%!    false)
%! assert_equals (...
%!    eq (infsupdec (1.0, inf, "trv"), infsupdec (1.0, inf, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (1.0, inf, "trv") == infsupdec (1.0, inf, "trv"), ...
%!    true)
%! assert_equals (...
%!    eq (infsupdec (1.0, 2.4, "def"), infsupdec (1.0, inf, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.4, "def") == infsupdec (1.0, inf, "trv"), ...
%!    false)
%! assert_equals (...
%!    eq (infsupdec (-inf, 2.0, "trv"), infsupdec (-inf, 2.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-inf, 2.0, "trv") == infsupdec (-inf, 2.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    eq (infsupdec (-inf, 2.4, "def"), infsupdec (-inf, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (-inf, 2.4, "def") == infsupdec (-inf, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    eq (infsupdec (-2.0, 0.0, "trv"), infsupdec (-2.0, 0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-2.0, 0.0, "trv") == infsupdec (-2.0, 0.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    eq (infsupdec (-0.0, 2.0, "def"), infsupdec (0.0, 2.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-0.0, 2.0, "def") == infsupdec (0.0, 2.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    eq (infsupdec (-0.0, -0.0, "trv"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-0.0, -0.0, "trv") == infsupdec (0.0, 0.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    eq (infsupdec (-0.0, 0.0, "def"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-0.0, 0.0, "def") == infsupdec (0.0, 0.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    eq (infsupdec (0.0, -0.0, "trv"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (0.0, -0.0, "trv") == infsupdec (0.0, 0.0, "trv"), ...
%!    true)

%!test "minimal_subset_test";
%! assert_equals (...
%!    subset (infsup (), infsup ()), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsup (0.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsup (-0.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsup (-0.1, 1.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsup (-0.1, 0.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsup (-0.1, -0.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (0.0, 4.0), infsup ()), ...
%!    false)
%! assert_equals (...
%!    subset (infsup (-0.0, 4.0), infsup ()), ...
%!    false)
%! assert_equals (...
%!    subset (infsup (-0.1, 1.0), infsup ()), ...
%!    false)
%! assert_equals (...
%!    subset (infsup (-inf, inf), infsup ()), ...
%!    false)
%! assert_equals (...
%!    subset (infsup (0.0, 4.0), infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (-0.0, 4.0), infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (-0.1, 1.0), infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (-inf, inf), infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (1.0, 2.0), infsup (1.0, 2.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (1.0, 2.0), infsup (0.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (1.0, 2.0), infsup (-0.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (0.1, 0.2), infsup (0.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (0.1, 0.2), infsup (-0.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (-0.1, -0.1), infsup (-4.0, 3.4)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (0.0, 0.0), infsup (-0.0, -0.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (-0.0, -0.0), infsup (0.0, 0.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (-0.0, 0.0), infsup (0.0, 0.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (-0.0, 0.0), infsup (0.0, -0.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (0.0, -0.0), infsup (0.0, 0.0)), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (0.0, -0.0), infsup (-0.0, 0.0)), ...
%!    true)

%!test "minimal_subset_dec_test";
%! assert_equals (...
%!    subset (infsup (), infsupdec (0.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsupdec (-0.0, 4.0, "def")), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsupdec (-0.1, 1.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsupdec (-0.1, 0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsupdec (-0.1, -0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsup (), infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (0.0, 4.0, "trv"), infsup ()), ...
%!    false)
%! assert_equals (...
%!    subset (infsupdec (-0.0, 4.0, "def"), infsup ()), ...
%!    false)
%! assert_equals (...
%!    subset (infsupdec (-0.1, 1.0, "trv"), infsup ()), ...
%!    false)
%! assert_equals (...
%!    subset (infsupdec (-inf, inf, "trv"), infsup ()), ...
%!    false)
%! assert_equals (...
%!    subset (infsupdec (0.0, 4.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (-0.0, 4.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (-0.1, 1.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (-inf, inf, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (1.0, 2.0, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (1.0, 2.0, "trv"), infsupdec (0.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (1.0, 2.0, "def"), infsupdec (-0.0, 4.0, "def")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (0.1, 0.2, "trv"), infsupdec (0.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (0.1, 0.2, "trv"), infsupdec (-0.0, 4.0, "def")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (-0.1, -0.1, "trv"), infsupdec (-4.0, 3.4, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (0.0, 0.0, "trv"), infsupdec (-0.0, -0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (-0.0, -0.0, "trv"), infsupdec (0.0, 0.0, "def")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (-0.0, 0.0, "trv"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (-0.0, 0.0, "trv"), infsupdec (0.0, -0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (0.0, -0.0, "def"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    subset (infsupdec (0.0, -0.0, "trv"), infsupdec (-0.0, 0.0, "trv")), ...
%!    true)

%!test "minimal_less_test";
%! assert_equals (...
%!    le (infsup (), infsup ()), ...
%!    true)

%! assert_equals (...
%!    infsup () <= infsup (), ...
%!    true)
%! assert_equals (...
%!    le (infsup (1.0, 2.0), infsup ()), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 2.0) <= infsup (), ...
%!    false)
%! assert_equals (...
%!    le (infsup (), infsup (1.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup () <= infsup (1.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    le (infsup (-inf, inf), infsup (-inf, inf)), ...
%!    true)

%! assert_equals (...
%!    infsup (-inf, inf) <= infsup (-inf, inf), ...
%!    true)
%! assert_equals (...
%!    le (infsup (1.0, 2.0), infsup (-inf, inf)), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 2.0) <= infsup (-inf, inf), ...
%!    false)
%! assert_equals (...
%!    le (infsup (0.0, 2.0), infsup (-inf, inf)), ...
%!    false)

%! assert_equals (...
%!    infsup (0.0, 2.0) <= infsup (-inf, inf), ...
%!    false)
%! assert_equals (...
%!    le (infsup (-0.0, 2.0), infsup (-inf, inf)), ...
%!    false)

%! assert_equals (...
%!    infsup (-0.0, 2.0) <= infsup (-inf, inf), ...
%!    false)
%! assert_equals (...
%!    le (infsup (-inf, inf), infsup (1.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (-inf, inf) <= infsup (1.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    le (infsup (-inf, inf), infsup (0.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (-inf, inf) <= infsup (0.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    le (infsup (-inf, inf), infsup (-0.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (-inf, inf) <= infsup (-0.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    le (infsup (0.0, 2.0), infsup (0.0, 2.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (0.0, 2.0) <= infsup (0.0, 2.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (0.0, 2.0), infsup (-0.0, 2.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (0.0, 2.0) <= infsup (-0.0, 2.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (0.0, 2.0), infsup (1.0, 2.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (0.0, 2.0) <= infsup (1.0, 2.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (-0.0, 2.0), infsup (1.0, 2.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-0.0, 2.0) <= infsup (1.0, 2.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (1.0, 2.0), infsup (1.0, 2.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (1.0, 2.0) <= infsup (1.0, 2.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (1.0, 2.0), infsup (3.0, 4.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (1.0, 2.0) <= infsup (3.0, 4.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (1.0, 3.5), infsup (3.0, 4.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (1.0, 3.5) <= infsup (3.0, 4.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (1.0, 4.0), infsup (3.0, 4.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (1.0, 4.0) <= infsup (3.0, 4.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (-2.0, -1.0), infsup (-2.0, -1.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-2.0, -1.0) <= infsup (-2.0, -1.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (-3.0, -1.5), infsup (-2.0, -1.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-3.0, -1.5) <= infsup (-2.0, -1.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (0.0, 0.0), infsup (-0.0, -0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (0.0, 0.0) <= infsup (-0.0, -0.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (-0.0, -0.0), infsup (0.0, 0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-0.0, -0.0) <= infsup (0.0, 0.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (-0.0, 0.0), infsup (0.0, 0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-0.0, 0.0) <= infsup (0.0, 0.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (-0.0, 0.0), infsup (0.0, -0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-0.0, 0.0) <= infsup (0.0, -0.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (0.0, -0.0), infsup (0.0, 0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (0.0, -0.0) <= infsup (0.0, 0.0), ...
%!    true)
%! assert_equals (...
%!    le (infsup (0.0, -0.0), infsup (-0.0, 0.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (0.0, -0.0) <= infsup (-0.0, 0.0), ...
%!    true)

%!test "minimal_less_dec_test";
%! assert_equals (...
%!    le (infsupdec (1.0, 2.0, "trv"), infsup ()), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "trv") <= infsup (), ...
%!    false)
%! assert_equals (...
%!    le (infsup (), infsupdec (1.0, 2.0, "def")), ...
%!    false)

%! assert_equals (...
%!    infsup () <= infsupdec (1.0, 2.0, "def"), ...
%!    false)
%! assert_equals (...
%!    le (infsupdec (1.0, 2.0, "trv"), infsup ()), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "trv") <= infsup (), ...
%!    false)
%! assert_equals (...
%!    le (infsup (), infsupdec (1.0, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsup () <= infsupdec (1.0, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    le (infsupdec (-inf, inf, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-inf, inf, "trv") <= infsupdec (-inf, inf, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (1.0, 2.0, "def"), infsupdec (-inf, inf, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "def") <= infsupdec (-inf, inf, "trv"), ...
%!    false)
%! assert_equals (...
%!    le (infsupdec (0.0, 2.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (0.0, 2.0, "trv") <= infsupdec (-inf, inf, "trv"), ...
%!    false)
%! assert_equals (...
%!    le (infsupdec (-0.0, 2.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (-0.0, 2.0, "trv") <= infsupdec (-inf, inf, "trv"), ...
%!    false)
%! assert_equals (...
%!    le (infsupdec (-inf, inf, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (-inf, inf, "trv") <= infsupdec (1.0, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    le (infsupdec (-inf, inf, "trv"), infsupdec (0.0, 2.0, "def")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (-inf, inf, "trv") <= infsupdec (0.0, 2.0, "def"), ...
%!    false)
%! assert_equals (...
%!    le (infsupdec (-inf, inf, "trv"), infsupdec (-0.0, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (-inf, inf, "trv") <= infsupdec (-0.0, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    le (infsupdec (0.0, 2.0, "trv"), infsupdec (0.0, 2.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (0.0, 2.0, "trv") <= infsupdec (0.0, 2.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (0.0, 2.0, "trv"), infsupdec (-0.0, 2.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (0.0, 2.0, "trv") <= infsupdec (-0.0, 2.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (0.0, 2.0, "def"), infsupdec (1.0, 2.0, "def")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (0.0, 2.0, "def") <= infsupdec (1.0, 2.0, "def"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (-0.0, 2.0, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-0.0, 2.0, "trv") <= infsupdec (1.0, 2.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (1.0, 2.0, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "trv") <= infsupdec (1.0, 2.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (1.0, 2.0, "trv"), infsupdec (3.0, 4.0, "def")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "trv") <= infsupdec (3.0, 4.0, "def"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (1.0, 3.5, "trv"), infsupdec (3.0, 4.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (1.0, 3.5, "trv") <= infsupdec (3.0, 4.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (1.0, 4.0, "trv"), infsupdec (3.0, 4.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (1.0, 4.0, "trv") <= infsupdec (3.0, 4.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (-2.0, -1.0, "trv"), infsupdec (-2.0, -1.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-2.0, -1.0, "trv") <= infsupdec (-2.0, -1.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (-3.0, -1.5, "trv"), infsupdec (-2.0, -1.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-3.0, -1.5, "trv") <= infsupdec (-2.0, -1.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (0.0, 0.0, "trv"), infsupdec (-0.0, -0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (0.0, 0.0, "trv") <= infsupdec (-0.0, -0.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (-0.0, -0.0, "trv"), infsupdec (0.0, 0.0, "def")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-0.0, -0.0, "trv") <= infsupdec (0.0, 0.0, "def"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (-0.0, 0.0, "trv"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-0.0, 0.0, "trv") <= infsupdec (0.0, 0.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (-0.0, 0.0, "trv"), infsupdec (0.0, -0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-0.0, 0.0, "trv") <= infsupdec (0.0, -0.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (0.0, -0.0, "def"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (0.0, -0.0, "def") <= infsupdec (0.0, 0.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    le (infsupdec (0.0, -0.0, "trv"), infsupdec (-0.0, 0.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (0.0, -0.0, "trv") <= infsupdec (-0.0, 0.0, "trv"), ...
%!    true)

%!test "minimal_precedes_test";
%! assert_equals (...
%!    precedes (infsup (), infsup (3.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (3.0, 4.0), infsup ()), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (), infsup ()), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (1.0, 2.0), infsup (-inf, inf)), ...
%!    false)
%! assert_equals (...
%!    precedes (infsup (0.0, 2.0), infsup (-inf, inf)), ...
%!    false)
%! assert_equals (...
%!    precedes (infsup (-0.0, 2.0), infsup (-inf, inf)), ...
%!    false)
%! assert_equals (...
%!    precedes (infsup (-inf, inf), infsup (1.0, 2.0)), ...
%!    false)
%! assert_equals (...
%!    precedes (infsup (-inf, inf), infsup (-inf, inf)), ...
%!    false)
%! assert_equals (...
%!    precedes (infsup (1.0, 2.0), infsup (3.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (1.0, 3.0), infsup (3.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (-3.0, -1.0), infsup (-1.0, 0.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (-3.0, -1.0), infsup (-1.0, -0.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (1.0, 3.5), infsup (3.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    precedes (infsup (1.0, 4.0), infsup (3.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    precedes (infsup (-3.0, -0.1), infsup (-1.0, 0.0)), ...
%!    false)
%! assert_equals (...
%!    precedes (infsup (0.0, 0.0), infsup (-0.0, -0.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (-0.0, -0.0), infsup (0.0, 0.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (-0.0, 0.0), infsup (0.0, 0.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (-0.0, 0.0), infsup (0.0, -0.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (0.0, -0.0), infsup (0.0, 0.0)), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (0.0, -0.0), infsup (-0.0, 0.0)), ...
%!    true)

%!test "minimal_precedes_dec_test";
%! assert_equals (...
%!    precedes (infsup (), infsupdec (3.0, 4.0, "def")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (3.0, 4.0, "trv"), infsup ()), ...
%!    true)
%! assert_equals (...
%!    precedes (infsup (), infsupdec (3.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (3.0, 4.0, "trv"), infsup ()), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (1.0, 2.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    precedes (infsupdec (0.0, 2.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    precedes (infsupdec (-0.0, 2.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    precedes (infsupdec (-inf, inf, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    precedes (infsupdec (-inf, inf, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    precedes (infsupdec (1.0, 2.0, "trv"), infsupdec (3.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (1.0, 3.0, "trv"), infsupdec (3.0, 4.0, "def")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (-3.0, -1.0, "def"), infsupdec (-1.0, 0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (-3.0, -1.0, "trv"), infsupdec (-1.0, -0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (1.0, 3.5, "trv"), infsupdec (3.0, 4.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    precedes (infsupdec (1.0, 4.0, "trv"), infsupdec (3.0, 4.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    precedes (infsupdec (-3.0, -0.1, "trv"), infsupdec (-1.0, 0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    precedes (infsupdec (0.0, 0.0, "trv"), infsupdec (-0.0, -0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (-0.0, -0.0, "trv"), infsupdec (0.0, 0.0, "def")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (-0.0, 0.0, "trv"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (-0.0, 0.0, "def"), infsupdec (0.0, -0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (0.0, -0.0, "trv"), infsupdec (0.0, 0.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    precedes (infsupdec (0.0, -0.0, "trv"), infsupdec (-0.0, 0.0, "trv")), ...
%!    true)

%!test "minimal_interior_test";
%! assert_equals (...
%!    interior (infsup (), infsup ()), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (), infsup (0.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (0.0, 4.0), infsup ()), ...
%!    false)
%! assert_equals (...
%!    interior (infsup (-inf, inf), infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (0.0, 4.0), infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (), infsup (-inf, inf)), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (-inf, inf), infsup (0.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    interior (infsup (0.0, 4.0), infsup (0.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    interior (infsup (1.0, 2.0), infsup (0.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (-2.0, 2.0), infsup (-2.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    interior (infsup (-0.0, -0.0), infsup (-2.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (0.0, 0.0), infsup (-2.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (0.0, 0.0), infsup (-0.0, -0.0)), ...
%!    false)
%! assert_equals (...
%!    interior (infsup (0.0, 4.4), infsup (0.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    interior (infsup (-1.0, -1.0), infsup (0.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    interior (infsup (2.0, 2.0), infsup (-2.0, -1.0)), ...
%!    false)

%!test "minimal_interior_dec_test";
%! assert_equals (...
%!    interior (infsup (), infsupdec (0.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    interior (infsupdec (0.0, 4.0, "def"), infsup ()), ...
%!    false)
%! assert_equals (...
%!    interior (infsupdec (0.0, 4.0, "trv"), infsup ()), ...
%!    false)
%! assert_equals (...
%!    interior (infsupdec (-inf, inf, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    interior (infsupdec (0.0, 4.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    interior (infsup (), infsupdec (-inf, inf, "trv")), ...
%!    true)
%! assert_equals (...
%!    interior (infsupdec (-inf, inf, "trv"), infsupdec (0.0, 4.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    interior (infsupdec (0.0, 4.0, "trv"), infsupdec (0.0, 4.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    interior (infsupdec (1.0, 2.0, "def"), infsupdec (0.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    interior (infsupdec (-2.0, 2.0, "trv"), infsupdec (-2.0, 4.0, "def")), ...
%!    false)
%! assert_equals (...
%!    interior (infsupdec (-0.0, -0.0, "trv"), infsupdec (-2.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    interior (infsupdec (0.0, 0.0, "def"), infsupdec (-2.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    interior (infsupdec (0.0, 0.0, "trv"), infsupdec (-0.0, -0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    interior (infsupdec (0.0, 4.4, "trv"), infsupdec (0.0, 4.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    interior (infsupdec (-1.0, -1.0, "trv"), infsupdec (0.0, 4.0, "def")), ...
%!    false)
%! assert_equals (...
%!    interior (infsupdec (2.0, 2.0, "def"), infsupdec (-2.0, -1.0, "trv")), ...
%!    false)

%!test "minimal_strictLess_test";
%! assert_equals (...
%!    lt (infsup (), infsup ()), ...
%!    true)

%! assert_equals (...
%!    infsup () < infsup (), ...
%!    true)
%! assert_equals (...
%!    lt (infsup (1.0, 2.0), infsup ()), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 2.0) < infsup (), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (), infsup (1.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup () < infsup (1.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (-inf, inf), infsup (-inf, inf)), ...
%!    true)

%! assert_equals (...
%!    infsup (-inf, inf) < infsup (-inf, inf), ...
%!    true)
%! assert_equals (...
%!    lt (infsup (1.0, 2.0), infsup (-inf, inf)), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 2.0) < infsup (-inf, inf), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (-inf, inf), infsup (1.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (-inf, inf) < infsup (1.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (1.0, 2.0), infsup (1.0, 2.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 2.0) < infsup (1.0, 2.0), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (1.0, 2.0), infsup (3.0, 4.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (1.0, 2.0) < infsup (3.0, 4.0), ...
%!    true)
%! assert_equals (...
%!    lt (infsup (1.0, 3.5), infsup (3.0, 4.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (1.0, 3.5) < infsup (3.0, 4.0), ...
%!    true)
%! assert_equals (...
%!    lt (infsup (1.0, 4.0), infsup (3.0, 4.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (1.0, 4.0) < infsup (3.0, 4.0), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (0.0, 4.0), infsup (0.0, 4.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (0.0, 4.0) < infsup (0.0, 4.0), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (-0.0, 4.0), infsup (0.0, 4.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (-0.0, 4.0) < infsup (0.0, 4.0), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (-2.0, -1.0), infsup (-2.0, -1.0)), ...
%!    false)

%! assert_equals (...
%!    infsup (-2.0, -1.0) < infsup (-2.0, -1.0), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (-3.0, -1.5), infsup (-2.0, -1.0)), ...
%!    true)

%! assert_equals (...
%!    infsup (-3.0, -1.5) < infsup (-2.0, -1.0), ...
%!    true)

%!test "minimal_strictLess_dec_test";
%! assert_equals (...
%!    lt (infsupdec (1.0, 2.0, "trv"), infsup ()), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "trv") < infsup (), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (), infsupdec (1.0, 2.0, "def")), ...
%!    false)

%! assert_equals (...
%!    infsup () < infsupdec (1.0, 2.0, "def"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (1.0, 2.0, "def"), infsup ()), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "def") < infsup (), ...
%!    false)
%! assert_equals (...
%!    lt (infsup (), infsupdec (1.0, 2.0, "def")), ...
%!    false)

%! assert_equals (...
%!    infsup () < infsupdec (1.0, 2.0, "def"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (-inf, inf, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-inf, inf, "trv") < infsupdec (-inf, inf, "trv"), ...
%!    true)
%! assert_equals (...
%!    lt (infsupdec (1.0, 2.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "trv") < infsupdec (-inf, inf, "trv"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (-inf, inf, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (-inf, inf, "trv") < infsupdec (1.0, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (1.0, 2.0, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "trv") < infsupdec (1.0, 2.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (1.0, 2.0, "trv"), infsupdec (3.0, 4.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (1.0, 2.0, "trv") < infsupdec (3.0, 4.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    lt (infsupdec (1.0, 3.5, "def"), infsupdec (3.0, 4.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (1.0, 3.5, "def") < infsupdec (3.0, 4.0, "trv"), ...
%!    true)
%! assert_equals (...
%!    lt (infsupdec (1.0, 4.0, "trv"), infsupdec (3.0, 4.0, "def")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (1.0, 4.0, "trv") < infsupdec (3.0, 4.0, "def"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (0.0, 4.0, "trv"), infsupdec (0.0, 4.0, "def")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (0.0, 4.0, "trv") < infsupdec (0.0, 4.0, "def"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (-0.0, 4.0, "def"), infsupdec (0.0, 4.0, "trv")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (-0.0, 4.0, "def") < infsupdec (0.0, 4.0, "trv"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (-2.0, -1.0, "def"), infsupdec (-2.0, -1.0, "def")), ...
%!    false)

%! assert_equals (...
%!    infsupdec (-2.0, -1.0, "def") < infsupdec (-2.0, -1.0, "def"), ...
%!    false)
%! assert_equals (...
%!    lt (infsupdec (-3.0, -1.5, "trv"), infsupdec (-2.0, -1.0, "trv")), ...
%!    true)

%! assert_equals (...
%!    infsupdec (-3.0, -1.5, "trv") < infsupdec (-2.0, -1.0, "trv"), ...
%!    true)

%!test "minimal_strictPrecedes_test";
%! assert_equals (...
%!    strictprecedes (infsup (), infsup (3.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsup (3.0, 4.0), infsup ()), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsup (), infsup ()), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsup (1.0, 2.0), infsup (-inf, inf)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (-inf, inf), infsup (1.0, 2.0)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (-inf, inf), infsup (-inf, inf)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (1.0, 2.0), infsup (3.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsup (1.0, 3.0), infsup (3.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (-3.0, -1.0), infsup (-1.0, 0.0)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (-3.0, -0.0), infsup (0.0, 1.0)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (-3.0, 0.0), infsup (-0.0, 1.0)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (1.0, 3.5), infsup (3.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (1.0, 4.0), infsup (3.0, 4.0)), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsup (-3.0, -0.1), infsup (-1.0, 0.0)), ...
%!    false)

%!test "minimal_strictPrecedes_dec_test";
%! assert_equals (...
%!    strictprecedes (infsup (), infsupdec (3.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsupdec (3.0, 4.0, "def"), infsup ()), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsup (), infsupdec (3.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsupdec (3.0, 4.0, "def"), infsup ()), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsupdec (1.0, 2.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (-inf, inf, "trv"), infsupdec (1.0, 2.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (-inf, inf, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (1.0, 2.0, "trv"), infsupdec (3.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    strictprecedes (infsupdec (1.0, 3.0, "def"), infsupdec (3.0, 4.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (-3.0, -1.0, "trv"), infsupdec (-1.0, 0.0, "def")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (-3.0, -0.0, "def"), infsupdec (0.0, 1.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (-3.0, 0.0, "trv"), infsupdec (-0.0, 1.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (1.0, 3.5, "trv"), infsupdec (3.0, 4.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (1.0, 4.0, "trv"), infsupdec (3.0, 4.0, "def")), ...
%!    false)
%! assert_equals (...
%!    strictprecedes (infsupdec (-3.0, -0.1, "trv"), infsupdec (-1.0, 0.0, "trv")), ...
%!    false)

%!test "minimal_disjoint_test";
%! assert_equals (...
%!    disjoint (infsup (), infsup (3.0, 4.0)), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsup (3.0, 4.0), infsup ()), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsup (), infsup ()), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsup (3.0, 4.0), infsup (1.0, 2.0)), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsup (0.0, 0.0), infsup (-0.0, -0.0)), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsup (0.0, -0.0), infsup (-0.0, 0.0)), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsup (3.0, 4.0), infsup (1.0, 7.0)), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsup (3.0, 4.0), infsup (-inf, inf)), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsup (-inf, inf), infsup (1.0, 7.0)), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsup (-inf, inf), infsup (-inf, inf)), ...
%!    false)

%!test "minimal_disjoint_dec_test";
%! assert_equals (...
%!    disjoint (infsup (), infsupdec (3.0, 4.0, "def")), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsupdec (3.0, 4.0, "trv"), infsup ()), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsup (), infsupdec (3.0, 4.0, "trv")), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsupdec (3.0, 4.0, "trv"), infsup ()), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsupdec (3.0, 4.0, "trv"), infsupdec (1.0, 2.0, "def")), ...
%!    true)
%! assert_equals (...
%!    disjoint (infsupdec (0.0, 0.0, "trv"), infsupdec (-0.0, -0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsupdec (0.0, -0.0, "trv"), infsupdec (-0.0, 0.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsupdec (3.0, 4.0, "def"), infsupdec (1.0, 7.0, "def")), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsupdec (3.0, 4.0, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsupdec (-inf, inf, "trv"), infsupdec (1.0, 7.0, "trv")), ...
%!    false)
%! assert_equals (...
%!    disjoint (infsupdec (-inf, inf, "trv"), infsupdec (-inf, inf, "trv")), ...
%!    false)
%!shared
%!  ## Re-Enable warnings when creating NaIs
%!  warning ("on", "interval:NaI")
