##
## Copyright 2013 - 2015 Marco Nehmeier (nehmeier@informatik.uni-wuerzburg.de)
## Copyright 2015 Oliver Heimlich (oheim@posteo.de)
## 
## Original author: Marco Nehmeier (unit tests in libieeep1788)
## Converted into portable ITL format by Oliver Heimlich with minor corrections.
## 
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
## 
##     http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
%!shared
%!  ## Disable warnings when creating NaIs
%!  warning ("off", "interval:NaI")
%! ## Test library imports
%!function s = to_string (x)
%!    if (isnumeric (x))
%!        s = num2str (x);
%!    elseif (isa (x, 'infsup'))
%!        s = intervaltotext (x);
%!    else
%!        # x probably is a char.
%!        s = x;
%!    endif
%!endfunction
%
%!function assert_equals (x, y)
%!    if (isa (x, "infsup"))
%!        assert (eq (x, y));
%!    else
%!        assert (isequal (x, y));
%!    endif
%!endfunction
%
%!function n = decval (dec)
%! n = find (strcmp (dec, {"ill", "trv", "def", "dac", "com"}));
%!endfunction

%!test "minimal_intersection_test";
%! assert_equals (...
%!    and (infsup (1.0, 3.0), infsup (2.1, 4.0)), ...
%!    infsup (2.1, 3.0))
%! assert_equals (...
%!    and (infsup (1.0, 3.0), infsup (3.0, 4.0)), ...
%!    infsup (3.0, 3.0))
%! assert_equals (...
%!    and (infsup (1.0, 3.0), infsup ()), ...
%!    infsup ())
%! assert_equals (...
%!    and (infsup (-inf, inf), infsup ()), ...
%!    infsup ())
%! assert_equals (...
%!    and (infsup (1.0, 3.0), infsup (-inf, inf)), ...
%!    infsup (1.0, 3.0))

%!test "minimal_intersection_dec_test";
%! assert_equals (...
%!    and (infsupdec (1.0, 3.0, "com"), infsupdec (2.1, 4.0, "com")), ...
%!    infsupdec (2.1, 3.0, "trv"))

%! assert_equals (...
%!    (decorationpart (and (infsupdec (1.0, 3.0, "com"), infsupdec (2.1, 4.0, "com"))) {1}), ...
%!    (decorationpart (infsupdec (2.1, 3.0, "trv")) {1}))
%! assert_equals (...
%!    and (infsupdec (1.0, 3.0, "dac"), infsupdec (3.0, 4.0, "def")), ...
%!    infsupdec (3.0, 3.0, "trv"))

%! assert_equals (...
%!    (decorationpart (and (infsupdec (1.0, 3.0, "dac"), infsupdec (3.0, 4.0, "def"))) {1}), ...
%!    (decorationpart (infsupdec (3.0, 3.0, "trv")) {1}))
%! assert_equals (...
%!    and (infsupdec (1.0, 3.0, "def"), infsup ()), ...
%!    infsup ())
%! assert_equals (...
%!    and (infsupdec (entire, "def"), infsup ()), ...
%!    infsup ())
%! assert_equals (...
%!    and (infsupdec (1.0, 3.0, "dac"), infsupdec (entire, "def")), ...
%!    infsupdec (1.0, 3.0, "trv"))

%! assert_equals (...
%!    (decorationpart (and (infsupdec (1.0, 3.0, "dac"), infsupdec (entire, "def"))) {1}), ...
%!    (decorationpart (infsupdec (1.0, 3.0, "trv")) {1}))

%!test "minimal_convexHull_test";
%! assert_equals (...
%!    or (infsup (1.0, 3.0), infsup (2.1, 4.0)), ...
%!    infsup (1.0, 4.0))
%! assert_equals (...
%!    or (infsup (1.0, 1.0), infsup (2.1, 4.0)), ...
%!    infsup (1.0, 4.0))
%! assert_equals (...
%!    or (infsup (1.0, 3.0), infsup ()), ...
%!    infsup (1.0, 3.0))
%! assert_equals (...
%!    or (infsup (), infsup ()), ...
%!    infsup ())
%! assert_equals (...
%!    or (infsup (1.0, 3.0), infsup (-inf, inf)), ...
%!    infsup (-inf, inf))

%!test "minimal_convexHull_dec_test";
%! assert_equals (...
%!    or (infsupdec (1.0, 3.0, "trv"), infsupdec (2.1, 4.0, "trv")), ...
%!    infsupdec (1.0, 4.0, "trv"))

%! assert_equals (...
%!    (decorationpart (or (infsupdec (1.0, 3.0, "trv"), infsupdec (2.1, 4.0, "trv"))) {1}), ...
%!    (decorationpart (infsupdec (1.0, 4.0, "trv")) {1}))
%! assert_equals (...
%!    or (infsupdec (1.0, 1.0, "trv"), infsupdec (2.1, 4.0, "trv")), ...
%!    infsupdec (1.0, 4.0, "trv"))

%! assert_equals (...
%!    (decorationpart (or (infsupdec (1.0, 1.0, "trv"), infsupdec (2.1, 4.0, "trv"))) {1}), ...
%!    (decorationpart (infsupdec (1.0, 4.0, "trv")) {1}))
%! assert_equals (...
%!    or (infsupdec (1.0, 3.0, "trv"), infsup ()), ...
%!    infsupdec (1.0, 3.0, "trv"))

%! assert_equals (...
%!    (decorationpart (or (infsupdec (1.0, 3.0, "trv"), infsup ())) {1}), ...
%!    (decorationpart (infsupdec (1.0, 3.0, "trv")) {1}))
%! assert_equals (...
%!    or (infsup (), infsup ()), ...
%!    infsup ())
%! assert_equals (...
%!    or (infsupdec (1.0, 3.0, "trv"), infsupdec (entire, "def")), ...
%!    infsupdec (entire, "trv"))
%!shared
%!  ## Re-Enable warnings when creating NaIs
%!  warning ("on", "interval:NaI")
